name: deploy

on:
  pull_request:
  workflow_dispatch:
    inputs:
      app_env:
        description: "Target environment"
        type: choice
        required: true
        options:
          - dev
          - test
          - prod
      image_tag:
        description: "Backend image tag (e.g., sha-<full_sha> or vX.Y.Z)"
        type: string
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
concurrency:
  group: deploy-${{ inputs.app_env || 'dev' }}
  cancel-in-progress: false
env:
  TF_VERSION: 1.12.2
  TF_LOG: ERROR
  AZURE_REGION: Canada Central
jobs:
  deploy:
    runs-on: ubuntu-24.04
    #needs: [builds]
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    environment: ${{ inputs.app_env || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Make deploy script executable
        shell: bash
        run: chmod +x ./infra/terraform/deploy-terraform.sh

      - name: Compute backend image
        id: image
        shell: bash
        run: |
          BACKEND_IMAGE="ghcr.io/${{ github.repository }}/backend:latest"
          FLYWAY_IMAGE="ghcr.io/${{ github.repository }}/migrations:latest"
          KEYCLOAK_IMAGE="ghcr.io/${{ github.repository }}/keycloak:latest"
          echo "backend-image=$BACKEND_IMAGE" >> $GITHUB_OUTPUT
          echo "flyway-image=$FLYWAY_IMAGE" >> $GITHUB_OUTPUT
          echo "keycloak-image=$KEYCLOAK_IMAGE" >> $GITHUB_OUTPUT

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Terraform
        shell: bash
        working-directory: infra/terraform
        env:
          CI: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_USE_OIDC: true
          BACKEND_RESOURCE_GROUP: ${{ secrets.TFSTATE_RESOURCE_GROUP }}
          BACKEND_STORAGE_ACCOUNT: ${{ vars.TFSTATE_STORAGE_ACCOUNT }}
          BACKEND_CONTAINER_NAME: ${{ secrets.TFSTATE_CONTAINER }}
          BACKEND_STATE_KEY: "expense-tracker.dev.tfstate"
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_postgres_admin_username: ${{ secrets.POSTGRES_ADMIN_USERNAME }}
          TF_VAR_postgres_admin_password: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          TF_VAR_backend_image: ${{ steps.image.outputs.backend-image }}
          TF_VAR_flyway_image: ${{ steps.image.outputs.flyway-image }}
          TF_VAR_keycloak_image: ${{ steps.image.outputs.keycloak-image }}
          TF_VAR_azure_resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          TF_VAR_ip_allow_list_cidrs: ${{ secrets.IP_ALLOW_LIST_CIDRS }}
        run: |
          ./deploy-terraform.sh apply -var-file=terraform.${{ inputs.app_env || 'dev' }}.tfvars
